services:
  web:
    build: ./frontend

    depends_on:
      - api

  api:
    build: ./backend/model
    ports: 
      - "5000:5000"
    depends_on:
      - database
  
  db:
    build: ./backend/database
    command: --max_allowed_packet=512M --connect_timeout=300
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pw
    ports:
      - "3306:3306"

  